[phases.setup]
nixPkgs = ["openjdk21", "maven"]

[phases.install]
cmds = ["cd backend && mvn clean install -DskipTests"]

[phases.build]
cmds = ["cd backend && mvn package -DskipTests"]

[start]
cmd = "cd backend && java -jar target/ledger-backend-0.0.1-SNAPSHOT.jar"
